Repository beyondDevelops/AnimalTalk, pull requests merged in 2022-12, with the labels that each got.

#5 style: prettier 설정 동기화 확인
  public/index.html
  src/App.js
  src/Test.js
  src/Test2.js
Labels: documentation

#6 style: Prettier 테스트 최종
  public/index.html
  src/Test.js
  src/Test2.js
Labels: documentation

#8 setting: react-router-dom 모듈설치
  package-lock.json
  package.json
Labels: pair

#9 chore: 폴더구조 및 라우터 설정
  src/App.js
  src/App.jsx
  src/components/.keep
  src/pages/Chat/Chat.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/MyProfile/MyProfile.jsx
  src/pages/NotFound/NotFound.jsx
  src/pages/OtherProfile/OtherProfile.jsx
  src/pages/PostCreate/PostCreate.jsx
  src/pages/SplashScreen/SplashScreen.jsx
  src/share/Footer.jsx
  src/share/Header.jsx
  src/share/Post.jsx
  src/share/ProfileSettion.jsx
  src/share/SimpleUserList.jsx
Labels: pair

#11 setting: Tailwind 환경 설정
  package-lock.json
  package.json
  postcss.config.js
  src/index.css
  src/index.js
  src/pages/Chat/Chat.jsx
  src/share/Footer.jsx
  tailwind.config.js
Labels: pair

#13 setting: 함수 포맷 변경
  src/App.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/MyProfile/MyProfile.jsx
  src/pages/NotFound/NotFound.jsx
  src/pages/OtherProfile/OtherProfile.jsx
  src/pages/PostCreate/PostCreate.jsx
  src/pages/SplashScreen/SplashScreen.jsx
  src/share/Footer.jsx
  src/share/Header.jsx
  src/share/Post.jsx
  src/share/ProfileSettion.jsx
  src/share/SimpleUserList.jsx
Labels: pair

#15 design: Tailwind 적용 확인
  postcss.config.js
  src/index.css
  src/pages/Chat/Chat.jsx
  src/share/Footer.jsx
  tailwind.config.js
Labels: pair, design, setting

#16 design: 버튼 공통 스타일 설정
  src/index.css
Labels: pair, design, setting

#17 design: 페이지 레이아웃
  src/index.css
Labels: pair, design, setting

#19 design: footer 레이아웃 완성
  src/share/Footer.jsx
Labels: pair, design, component

#24 design: 공통 스타일 및 페이지 레이아웃
  public/assets/img/icon-more-vertical-large.png
  public/assets/img/icon-more-vertical-small.png
  src/index.css
  src/pages/Chat/Chat.jsx
Labels: pair, design, rename, setting, chore

#34 feat: Splash Screen 화면 구현
  src/pages/SplashScreen/SplashScreen.jsx
Labels: design, markup, component

#38 feat: 로그인버튼 컴포넌트 생성 및 로그인 초기화면 구현
  src/components/LoginBtn/LoginBtn.jsx
  src/pages/Login/Login.jsx
Labels: bug, design, markup, component

#39 design: 유저 리스트 마크업 및 디자인
  src/share/SimpleUserList.jsx
Labels: design, markup, component, feat

#41 fix: border 변수읽지 못하는 버그 수정
  src/components/LoginBtn/LoginBtn.jsx
  src/pages/Login/Login.jsx
Labels: fix

#42 design: Post 컴포넌트 디자인 작업 및 Home main 요소 레이아웃 설정
  src/pages/Home/Home.jsx
  src/share/Post.jsx
Labels: design, component

#43 fix: Post 컴포넌트 수정사항 반영 중 발생한 props undefined 오류 해결 작업
  src/share/Post.jsx
Labels: fix

#45 fix: header, footer 크기 안줄어들게 수정
  src/share/Footer.jsx
  src/share/HeaderBind.jsx
Labels: fix

#46 design: Chat 페이지 중복 스타일 설정 제거
  src/pages/Chat/Chat.jsx
Labels: design

#55 design: Club 디자인 및 좌우 스크롤 버튼 기능 구현
  src/share/Club.jsx
Labels: design, component

#57 design: 유저 프로필 마크업 및 디자인
  src/share/UserProfile.jsx
Labels: design, markup, component, feat

#58 feat: 팔로우 버튼 클릭 시 취소 기능 추가
  src/share/SimpleUserList.jsx
Labels: feat, refactor

#60 Feat: 프로필 설정 컴포넌트 생성
  src/components/LoginAndJoin/LoginAndJoin.jsx
  src/pages/LoginEmail/LoginEmail.jsx
  src/pages/SignUp/SignUp.jsx
  src/share/ProfileSetting.jsx
  src/share/ProfileSettion.jsx
Labels: component, feat

#56 setting: tailwind-scrollbar-hide 모듈 설치
  package-lock.json
  package.json
  tailwind.config.js
Labels: setting

#61 feat: Club 컴포넌트 수정 및 SimpleClub 컴포넌트 생성, 이미지 크기에 따른 li 크기 디자인 재설정
  src/components/SimpleClub/SimpleClub.jsx
  src/share/Club.jsx
Labels: design, component, feat

#63 chore: 모듈 조립, 컴포넌트 수정
  src/App.jsx
  src/components/LoginBtn/LoginBtn.jsx
  src/index.css
  src/pages/Chat/Chat.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/MyProfile/MyProfile.jsx
  src/share/Footer.jsx
  src/share/HeaderBind.jsx
  src/share/SimpleUserList.jsx
Labels: pair, chore

#72 refactor: index.css 스타일 수정
  src/index.css
Labels: design, refactor

#76 refactor: 기본 페이지 레이아웃 및 index.css 수정에 따른 페이지 컴포넌트 스타일 수정
  src/components/SimpleClub/SimpleClub.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Home/Home.jsx
  src/pages/SplashScreen/SplashScreen.jsx
  src/share/Club.jsx
  src/share/SimpleUserList.jsx
  src/share/UserProfile.jsx
Labels: design, component, refactor

#78 refactor: HeaderBind.jsx header 스타일 수정
  src/share/HeaderBind.jsx
Labels: design, refactor

#79 refactor: Footer.jsx 스타일 수정
  src/share/Footer.jsx
Labels: design, refactor

#77 refactor: Poster.jsx 시맨틱 및 리플로우 현상 수정
  public/assets/img/icon-heart-off.png
  public/assets/img/icon-heart-on.png
  src/share/Post.jsx
Labels: component, feat, fix, refactor, rename

#82 refactor: LoginBtn.jsx파일 삭제후 Login.jsx에 하드코딩
  src/components/LoginBtn/LoginBtn.jsx
  src/pages/Login/Login.jsx
Labels: component, refactor, remove

#84 feat: 404페이지 구현
  src/pages/NotFound/NotFound.jsx
Labels: component, feat

#85 setting: tailwind.config.js color 변수화 및 index.css 에 적용
  src/index.css
  tailwind.config.js
Labels: design, refactor

#90 help: 이미지 캐러셀 구현 중 transform 작동 안 함
  src/share/Post.jsx
Labels: help wanted, design, component, feat

#89 help: 모달창 추가
  src/components/Modal/Modal.jsx
  src/components/ModalInfo/ModalInfo.jsx
  src/pages/MyProfile/MyProfile.jsx
  src/share/HeaderBind.jsx
Labels: help wanted, design, component, feat

#95 feat: URL에 따른 footer 이미지 변경
  src/share/Footer.jsx
Labels: feat

#93 feat: ChatRoom 라우터 및 컴포넌트 생성
  src/App.jsx
  src/components/ChatModule/ChatRoomFooter/ChatRoomFooter.jsx
  src/components/ChatModule/UserChat/UserChat.jsx
  src/pages/Chat/ChatRoom/ChatRoom.jsx
Labels: design, component, feat, rename

#97 design: 배경색 흰색으로 바꾼후 box-shadow적용
  src/components/Modal/Modal.jsx
  src/components/ModalInfo/ModalInfo.jsx
Labels: design

#98 feat: 게시글 작성 구현 - 이미지 업로드 및 텍스트 상자
  src/components/Textarea/Textarea.jsx
  src/pages/PostCreate/PostCreate.jsx
Labels: design, markup, component, feat

#99 ProfileShare 폴더 구조 변경
  src/share/ProfileShare/ProfileSetting/ProfileSetting.jsx
  src/share/ProfileShare/UserProfile/UserProfile.jsx
Labels: rename

#100 design: 뒷배경 blur처리 변경, 쓸데없는 코드 삭제
  src/components/Modal/Modal.jsx
  src/components/ModalInfo/ModalInfo.jsx
  src/pages/MyProfile/MyProfile.jsx
  src/share/HeaderBind.jsx
Labels: design, chore

#102 design: 전반적인 디자인 수정
  src/components/ChatModule/UserChat/UserChat.jsx
  src/components/LoginAndJoin/LoginAndJoin.jsx
  src/components/Modal/Modal.jsx
  src/components/ModalInfo/ModalInfo.jsx
  src/components/SimpleClub/SimpleClub.jsx
  src/index.css
  src/pages/Chat/Chat.jsx
  src/pages/Login/Login.jsx
  src/pages/NotFound/NotFound.jsx
  src/share/Footer.jsx
  src/share/HeaderBind.jsx
  src/share/Post.jsx
  src/share/ProfileShare/ProfileSetting/ProfileSetting.jsx
  src/share/ProfileShare/UserProfile/UserProfile.jsx
  src/share/SimpleUserList.jsx
  src/share/UserProfile.jsx
Labels: design, chore

#104 fix: text의 rem px로 변경
  src/index.css
Labels: fix

#105 fix: 하단부의 label 여백 클릭 시 작동 오류 해결
  src/pages/PostCreate/PostCreate.jsx
Labels: fix

#106 design: OtherProfile 페이지 조립 및 Post, PostAlbum, ModalPostImg 컴포넌트 구현
  src/App.jsx
  src/components/ModalPostImg/ModalPostImg.jsx
  src/components/PostTypeSelectBar/PostTypeSelectBar.jsx
  src/pages/OtherProfile/OtherProfile.jsx
  src/share/Post.jsx
  src/share/PostAlbum.jsx
Labels: design, component, feat

#109 fix: Post.jsx 106번 머지 충돌 이슈 해결을 위한 누락사항 복원
  src/share/Post.jsx
Labels: component, fix

#110 refactor: 이미지 캐러셀 px 대신 index로 관리
  src/pages/Home/Home.jsx
  src/pages/MyProfile/MyProfile.jsx
  src/share/Post.jsx
Labels: refactor, rename

#115 fix: App.jsx의 SignUp 파일 경로 수정
  src/App.jsx
Labels: fix

#116 feat: SimpleUserList 디자인 수정 및 클릭 이벤트 활성화(navigate)
  src/App.jsx
  src/pages/ChatList/ChatList.jsx
  src/shared/SimpleUserList/SimpleUserList.jsx
Labels: design, component, feat, chore

#118 feat: 로그인 api 기능 구현, token 관리, CheakAuth 기능 구현
  src/App.jsx
  src/api/axios.jsx
  src/components/CheckAuth/CheckAuth.jsx
  src/components/LoginAndSignup/LoginAndSignup.jsx
  src/pages/LoginEmail/LoginEmail.jsx
  src/pages/SignUp/SignUp.jsx
Labels: pair, component, feat

#120 setting: axios 모듈 설치
  package-lock.json
  package.json
Labels: pair, setting

#126 Feat/PostUpload 구현 및 axios, textarea 컴포넌트 수정
  src/api/axios.jsx
  src/components/Textarea/Textarea.jsx
  src/pages/PostUpload/PostUpload.jsx
Labels: component, feat, refactor

#127 refactor: HeaderSave 컴포넌트 props 수정 (isActive, disabled 속성 추가)
  src/shared/Header/HeaderSave.jsx
Labels: component, refactor

#128 feat: 이메일검증 구현, 입력값에 따라 버튼 비활성화 기능 구현
  src/pages/LoginEmail/LoginEmail.jsx
  src/pages/SignUp/SignUp.jsx
Labels: feat

#129 feat: Home 페이지 기능 구현
  src/components/NoFeed/NoFeed.jsx
  src/pages/Home/Home.jsx
  src/shared/Post/Post.jsx
Labels: component, feat

#132 feat: search 페이지 구현
  src/App.jsx
  src/pages/UserSearch/UserSearch.jsx
  src/shared/Header/HeaderSearch.jsx
  src/shared/SimpleUserList/SimpleUserList.jsx
Labels: component, feat

#136 fix: Post, ModalPostImg 컴포넌트 이미지 url 수정 작업
  src/components/ModalModule/ModalPostImg.jsx
  src/shared/Post/Post.jsx
Labels: component, fix

#137 fix: 사용자 프로필 기본 이미지 설정 및 Home, Search 페이지 디자인 수정 작업
  src/pages/Home/Home.jsx
  src/pages/UserSearch/UserSearch.jsx
  src/shared/Post/Post.jsx
  src/shared/SimpleUserList/SimpleUserList.jsx
Labels: design, component, fix, chore

#139 feat: 회원가입 기능 구현
  src/pages/SignUp/SignUp.jsx
  src/shared/Profile/ProfileSetting.jsx
Labels: question, feat, refactor

#147 Feat/포스트 수정 구현
  src/pages/PostUpload/PostUpload.jsx
Labels: feat

#141 refactor: 데이터 1회 요청시 갯수 제한을 위해 IntersectionObserver 사용
  src/hooks/useIntersect.jsx
  src/pages/Home/Home.jsx
Labels: component, feat, refactor, chore

#144 feat: 게시글 사용자 프로필 이미지 및 작성자 정보 클릭 시 해당 유저의 UserFeed 페이지로 이동 기능 구현
  src/shared/Post/Post.jsx
Labels: component, feat

#145 feat: UserFeed에서 하위 컴포넌트에 필요한 데이터 api 요청 및 전달
  src/components/SimpleClub/SimpleClub.jsx
  src/pages/UserFeed/MyProfile.jsx
  src/pages/UserFeed/UserFeed.jsx
  src/shared/Post/PostAlbum.jsx
  src/shared/Profile/UserProfile.jsx
  src/shared/UserClub/UserClub.jsx
Labels: component, feat

#148 chore: typo 에러 수정
  src/hooks/useIntersect.jsx
  src/pages/Home/Home.jsx
  src/pages/SignUp/SignUp.jsx
Labels: fix, chore

#154 fix: Home 컴포넌트 내 피드가 없는 경우 observerTarget의 노출로 인한 무한 호출 버그 수정
  src/pages/Home/Home.jsx
Labels: bug, fix

#155 feat: ContextAPI를 이용하여 사용자 프로필 정보를 전역으로 접근 가능하도록 하는 기능 구현
  src/components/CheckAuth/CheckAuth.jsx
  src/context/UserContext.jsx
Labels: feat

#157 feat: useContext를 이용하여 사용자 계정의 프로필 페이지로 이동하는 기능 구현
  src/shared/Footer/Footer.jsx
Labels: component, feat

#159 chore: btn-cancel 오타 수정
  src/index.css
Labels: chore

#151 feat: token과 userEmail유무에 따른 URL이동
  src/pages/SignUp/SignUp.jsx
  src/pages/SplashScreen/SplashScreen.jsx
  src/shared/Profile/ProfileSetting.jsx
Labels: feat

#162 design: splashScreen, LoginHome레이아웃 수정 및 index.css수정
  src/index.css
  src/pages/LoginHome/LoginHome.jsx
  src/pages/SplashScreen/SplashScreen.jsx
Labels: design

#163 feat: club 변수 초기 상태 null 설정에 따른 렌더링 이슈 해결
  src/pages/UserFeed/UserFeed.jsx
Labels: component, feat, fix

#168 chore: 화살표 함수 및 오타 수정
  src/pages/PostUpload/PostUpload.jsx
Labels: chore

#166 feat: club 게시글 수정 구현 완료 (api 연결 포함, 네비게이트는 수정 필요)
  src/pages/ClubUpload/ClubUpload.jsx
Labels: design, markup, component, feat

#169 design: SplashScreen 애니메이션 효과 추가
  src/pages/SplashScreen/SplashScreen.jsx
  tailwind.config.js
Labels: design

#171 chore: btn-cancel 오타 수정 반영
  src/shared/Profile/UserProfile.jsx
  src/shared/SimpleUserList/SimpleUserList.jsx
Labels: chore

#175 feat: UserFeed 팔로우 api 요청 및 Follow 페이지 연결 기능 구현
  src/pages/Follows/Follows.jsx
  src/pages/UserFeed/UserFeed.jsx
  src/shared/Header/HeaderFollow.jsx
  src/shared/Profile/UserProfile.jsx
Labels: design, component, feat

#178 fix: Post 컴포넌트 38번째 줄 postDate 변수를 createdAt에서 updatedAt을 기준으로 변경
  src/shared/Post/Post.jsx
Labels: fix

#179 fix: Home 페이지 최초 렌더링 시 10개 게시글 데이터 요청 api 동작 구동 기능 구현
  src/pages/Home/Home.jsx
Labels: bug

#185 remove: ProfileSetting.jsx, LoginAndSignup.jsx 파일 삭제
  src/components/LoginAndSignup/LoginAndSignup.jsx
  src/shared/Profile/ProfileSetting.jsx
Labels: remove

#184 feat: UserProfile 컴포넌트 버튼들 조건부 렌더링 적용 및 팔로우 여부에 따른 스타일링 작업
  src/shared/Profile/UserProfile.jsx
Labels: design, component, feat

#189 feat: chat페이지 더미데이터로 구현
  src/components/ChatDummyData/ChatDummyData.jsx
  src/pages/ChatList/ChatList.jsx
Labels: component, feat

#187 feat: 포스트 상세 페이지 구현 (댓글 리스트, 삭제, 신고)
  src/pages/PostDetail/PostChatList.jsx
  src/pages/PostDetail/PostChatModal.jsx
  src/pages/PostDetail/PostDetail.jsx
  src/pages/PostDetail/PostDetailForm.jsx
Labels: design, markup, component, feat

#188 feat: handleArrowBtnVisibility 함수 생성 및 Club 스크롤 버튼 UI, UX 수정
  src/shared/UserClub/UserClub.jsx
Labels: design, component, feat, fix

#194 feat: 불러오지 못하는 이미지 기본이미지로 대체
  src/shared/Profile/UserProfile.jsx
  src/shared/SimpleUserList/SimpleUserList.jsx
Labels: feat, fix, refactor

#198 Refactor/issue 195 이미지 경로 및 클럽 업로드 수정
  src/components/ModalModule/ModalPostImg.jsx
  src/components/SimpleClub/SimpleClub.jsx
  src/pages/ClubUpload/ClubUpload.jsx
  src/pages/PostUpload/PostUpload.jsx
  src/shared/Post/Post.jsx
  src/shared/Post/PostAlbum.jsx
  src/shared/UserClub/UserClub.jsx
Labels: fix, refactor
