Repository beyondDevelops/AnimalTalk, pull requests merged in 2023-01, with the labels that each got.

#201 refactor: 모달 포스트 이미지 컴포넌트 이미지 및 기능 리팩토링
  src/components/ModalModule/ModalPostImg.jsx
  src/pages/UserFeed/UserFeed.jsx
  src/shared/Post/Post.jsx
  src/shared/Post/PostAlbum.jsx
Labels: design, component, refactor

#204 feat: UserFeed 페이지 유저 피드 데이터 요청(getUserFeeds 함수) useIntersect hook 이용
  src/pages/UserFeed/UserFeed.jsx
Labels: feat, refactor

#206 chore: PR #203 ModalPoast를 ModalPost로 정정
  src/components/ModalModule/ModalPost.jsx
  src/shared/Post/Post.jsx
Labels: chore

#208 feat: 팔로우 페이지 구현
  src/pages/Follows/Follows.jsx
  src/shared/Profile/UserProfile.jsx
  src/shared/SimpleUserList/SimpleUserList.jsx
Labels: component, feat

#210 refactor/issue 209 삭제 모달창에 확인창 추가
  src/components/ModalModule/ModalPost.jsx
  src/pages/PostDetail/PostChatModal.jsx
  src/pages/PostDetail/PostDetailForm.jsx
  src/shared/Post/Post.jsx
Labels: design, refactor

#213 fix: SimpleUserList 컴포넌트 handleLink 및 props 에러에 따른 undefined 수정
  src/pages/UserSearch/UserSearch.jsx
  src/shared/SimpleUserList/SimpleUserList.jsx
Labels: bug, design, component, fix

#215 fix: props drilling에 따른 follow, unfollow 비동기 관리 문제 해결
  src/pages/UserFeed/UserFeed.jsx
Labels: component, fix

#216 fix: url이 부정확한 경우 x-box뜨는 버그 수정
  src/pages/EditProfile/EditProfile.jsx
Labels: fix

#218 feat: 좋아요 기능 구현 완료
  src/shared/Post/Post.jsx
Labels: feat

#220 프로필 이미지 업로드시 기본이미지 baseProfile로 대체
  src/pages/SignupProfile/SignupProfile.jsx
Labels: feat

#223 fix: postDataArr useState 초깃값 빈 배열 할당에 따른 로딩 지연 조건부 렌더링 삭제
  src/pages/UserFeed/UserFeed.jsx
Labels: fix

#231 feat: 로그아웃 기능 구현
  src/components/ModalModule/Modal.jsx
Labels: feat

#229 design: UserFeed 게시글이 없는 경우 대체 이미지 및 텍스트 스타일
  src/pages/UserFeed/UserFeed.jsx
Labels: design

#230 design: 리스트형, 앨범형 버튼 좌우 간격 16px margin 적용
  src/components/PostTypeSelectBar/PostTypeSelectBar.jsx
Labels: design, refactor

#232 bug: 게시글의 이미지인 post.image가 undefined인 경우 Cannot read properties of un…
  src/shared/Post/Post.jsx
Labels: bug

#237 design: UserProfile 레이아웃 및 스타일 조정
  src/index.css
  src/shared/Profile/UserProfile.jsx
Labels: design, fix, refactor

#238 refactor: btnRef이 사용되지 않음에 따라 제거하였음
  src/shared/UserClub/UserClub.jsx
Labels: refactor

#235 feat: 채팅방 나가기 모달 구현(작동x)
  src/components/ModalModule/ModalInfo.jsx
  src/pages/ChatRoom/ChatRoom.jsx
  src/shared/Header/HeaderChat.jsx
Labels: feat

#241 fix/issue 239 프로필 수정 및 타 유저에서 내 프로필로 이동시 화면 재렌더링 추가
  src/pages/EditProfile/EditProfile.jsx
  src/pages/UserFeed/UserFeed.jsx
  src/shared/Footer/Footer.jsx
  src/shared/Profile/UserProfile.jsx
Labels: fix

#245 fix: 프로필 수정 및 모임 만들기 부분에 조건부 렌더링 추가
  src/shared/Profile/UserProfile.jsx
Labels: fix

#242 refactor: 리스트형, 앨범형 삼항연산자 중복 사용으로 인한 코드 가독성 문제 해결
  src/pages/UserFeed/UserFeed.jsx
Labels: refactor

#246 feat: 공유하기 url 복사 기능 구현
  src/shared/Profile/UserProfile.jsx
Labels: design, component, feat

#249 refactor: UserClub의 버튼 색상 변경
  src/shared/UserClub/UserClub.jsx
Labels: design, refactor

#250 fix: #246에서의 버튼 스타일 작업 취소 - 기본 스타일로 이미 적용되어 있음
  src/shared/Profile/UserProfile.jsx
Labels: design, fix

#252 design: 프로필 이미지에 cover 속성 추가
  src/shared/Profile/UserProfile.jsx
Labels: design

#256 feat/issue 253 feat/issue 253 UserClub 페이지 구현 (수정/삭제)
  src/App.jsx
  src/components/SimpleClub/SimpleClub.jsx
  src/pages/ClubUpload/ClubUpload.jsx
  src/pages/UserFeed/UserFeed.jsx
  src/shared/UserClub/UserClub.jsx
  src/shared/UserClub/UserClubModal.jsx
Labels: design, markup, component, feat

#257 pair/issue 255 리드미 파일 작성 및 자잘한 오류 수정
  README.md
  src/components/ModalModule/ModalPost.jsx
  src/components/ModalModule/ModalPostImg.jsx
  src/index.css
  src/pages/EditProfile/EditProfile.jsx
  src/pages/PostDetail/PostDetailForm.jsx
  src/pages/PostUpload/PostUpload.jsx
  src/pages/SignupProfile/SignupProfile.jsx
  src/shared/Footer/Footer.jsx
  src/shared/Header/HeaderBasic.jsx
  src/shared/Header/HeaderChat.jsx
  src/shared/Header/HeaderFeed.jsx
  src/shared/Header/HeaderFollow.jsx
  src/shared/Header/HeaderSave.jsx
  src/shared/Header/HeaderSearch.jsx
  src/shared/Post/Post.jsx
  src/shared/Profile/UserProfile.jsx
  src/shared/UserClub/UserClub.jsx
  src/shared/UserClub/UserClubModal.jsx
Labels: pair, component, fix, docs, refactor

#261 bug: PostAlbum 컴포넌트 이미지 undefined 문제 해결을 위해 post.image에 true, false 확인
  src/shared/Post/PostAlbum.jsx
Labels: bug

#264 fix: setTimeout을 설정하여 findUser 함수 동작 딜레이 적용
  src/pages/UserSearch/UserSearch.jsx
Labels: fix

#269 build: git hub pages에 spa 적용하기
  public/404.html
  public/index.html
Labels: build

#271 deploy: 배포용 pr
  README.md
  src/components/CheckAuth/CheckAuth.jsx
  src/pages/ClubUpload/ClubUpload.jsx
  src/pages/UserFeed/UserFeed.jsx
  src/pages/UserSearch/UserSearch.jsx
  src/shared/Footer/Footer.jsx
  src/shared/Profile/UserProfile.jsx
Labels: build

#272 docs: README.md 파일 수정
  README.md
Labels: docs

#279 fix: 모임 소개 콤마 오류 및 게시글 삭제 렌더링 리베이스
  src/pages/UserFeed/UserFeed.jsx
  src/shared/UserClub/UserClubModal.jsx
Labels: fix

#280 build: 모임 콤마 오류 및 게시글 삭제 렌더링 리베이스 파일 머지
  src/pages/UserFeed/UserFeed.jsx
  src/shared/UserClub/UserClubModal.jsx
Labels: build

#281 chore: 이미지에 cover 속성 추가
  src/shared/UserClub/UserClubModal.jsx
Labels: chore

#282 build : 이미지 cover 속성 추가
  src/shared/UserClub/UserClubModal.jsx
Labels: build

#285 fix: 성능 및 권장사항 개선(폰트 및 이미지 파일)
  README.md
  public/assets/img/icon-home.png
  public/assets/img/icon-home.svg
  public/assets/img/icon-message-circle-line-footer.png
  public/assets/img/icon-message-circle-line-footer.svg
  public/assets/img/icon-message-circle-line-profile.png
  public/assets/img/icon-message-circle-line-profile.svg
  src/index.css
  src/shared/Footer/Footer.jsx
  src/shared/Post/Post.jsx
Labels: docs, rename

#287 fix: 성능 및 권장사항 개선(폰트 및 이미지 파일)
  README.md
  public/assets/img/icon-home.png
  public/assets/img/icon-home.svg
  public/assets/img/icon-message-circle-line-footer.png
  public/assets/img/icon-message-circle-line-footer.svg
  public/assets/img/icon-message-circle-line-profile.png
  public/assets/img/icon-message-circle-line-profile.svg
  src/index.css
  src/shared/Footer/Footer.jsx
  src/shared/Post/Post.jsx
Labels: fix, docs, rename, chore

#289 chore: 머지 싱크 확인
  README.md
  public/assets/img/icon-home.png
  public/assets/img/icon-home.svg
  public/assets/img/icon-message-circle-line-footer.png
  public/assets/img/icon-message-circle-line-footer.svg
  public/assets/img/icon-message-circle-line-profile.png
  public/assets/img/icon-message-circle-line-profile.svg
  src/index.css
  src/shared/Footer/Footer.jsx
  src/shared/Post/Post.jsx
Labels: build

#292 fix: main 머지 미반영 해결
  README.md
  public/assets/img/icon-home.png
  public/assets/img/icon-home.svg
  public/assets/img/icon-message-circle-line-footer.png
  public/assets/img/icon-message-circle-line-footer.svg
  public/assets/img/icon-message-circle-line-profile.png
  public/assets/img/icon-message-circle-line-profile.svg
  src/index.css
  src/shared/Footer/Footer.jsx
  src/shared/Post/Post.jsx
Labels: fix
